/**
 * Fetch legacy allotments (Apps Script CSV) and write Supabase INSERT SQL.
 * Usage: node scripts/generate_allotment_import_sql.js
 */
const fs = require('fs');
const path = require('path');

const SCRIPT_URL =
  process.env.STOCK_ALLOTMENT_SCRIPT_URL ||
  'https://script.google.com/macros/s/AKfycbxHxa_srh1nfhDTEf1eiXeRj-u2wr7qWiki1m5QIJ7FtWsaVRBVI7kDk37jeSE7ETOz/exec';

function parseCsvLine(line) {
  const out = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i++;
        } else inQuotes = false;
      } else cur += ch;
    } else if (ch === '"') inQuotes = true;
    else if (ch === ',') {
      out.push(cur);
      cur = '';
    } else cur += ch;
  }
  out.push(cur);
  return out;
}

function parseCsv(text) {
  const raw = String(text || '').replace(/^\uFEFF/, '').trim();
  if (!raw || raw.startsWith('<')) throw new Error('Not CSV (got HTML/empty)');
  const lines = raw.split(/\r?\n/).filter((l) => l.trim() !== '');
  const headers = parseCsvLine(lines[0]).map((h) => String(h || '').trim());
  if (!headers.includes('AllotmentNo')) throw new Error('Missing AllotmentNo header: ' + headers.join(','));
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const cols = parseCsvLine(lines[i]);
    const obj = {};
    headers.forEach((h, idx) => {
      obj[h] = cols[idx] != null ? cols[idx] : '';
    });
    if (!obj.AllotmentNo) continue;
    rows.push(obj);
  }
  return rows;
}

function sqlStr(v) {
  if (v == null || v === '') return "''";
  return "'" + String(v).replace(/'/g, "''") + "'";
}

function sqlNum(v) {
  if (v === '' || v == null) return 'NULL';
  const n = Number(String(v).replace(/,/g, ''));
  return Number.isNaN(n) ? 'NULL' : String(n);
}

function sqlTs(v) {
  if (!v || Number.isNaN(Date.parse(v))) return 'now()';
  return sqlStr(new Date(v).toISOString());
}

(async () => {
  const sep = SCRIPT_URL.includes('?') ? '&' : '?';
  const url = `${SCRIPT_URL}${sep}format=csv`;
  console.log('Fetching', url);
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error('HTTP ' + res.status);
  const text = await res.text();
  const rows = parseCsv(text);
  console.log('Parsed rows:', rows.length);

  const maxByYear = {};
  rows.forEach((r) => {
    const m = String(r.AllotmentNo || '').match(/MZO\/ALT\/(\d{4})\/(\d+)/i);
    if (!m) return;
    const y = Number(m[1]);
    const s = Number(m[2]);
    maxByYear[y] = Math.max(maxByYear[y] || 0, s);
  });

  const lines = [];
  lines.push('-- Import legacy Stock Allotments into mzo_insight.stock_allotments');
  lines.push('-- Generated by scripts/generate_allotment_import_sql.js');
  lines.push('-- Safe-ish: skips rows whose allotment_no already exists');
  lines.push('-- Run in Supabase SQL Editor');
  lines.push('');
  lines.push('BEGIN;');
  lines.push('');

  const BATCH = 50;
  for (let i = 0; i < rows.length; i += BATCH) {
    const chunk = rows.slice(i, i + BATCH);
    lines.push('INSERT INTO mzo_insight.stock_allotments (');
    lines.push(
      '  allotment_no, date, movement_type, from_store, from_plant_code, division, plant_code,'
    );
    lines.push(
      '  material_code, material_description, unit, present_stock_div, source_stock_at_allot,'
    );
    lines.push('  zone_stock_at_allot, allotted_qty, remarks, created_by, created_at');
    lines.push(')');
    lines.push('SELECT * FROM (VALUES');
    chunk.forEach((r, idx) => {
      const comma = idx === chunk.length - 1 ? '' : ',';
      lines.push(
        `  (${sqlStr(r.AllotmentNo)}, ${sqlStr(String(r.Date || '').slice(0, 10))}, ${sqlStr(r.MovementType)}, ` +
          `${sqlStr(r.FromStore)}, ${sqlStr(r.FromPlantCode)}, ${sqlStr(r.Division)}, ${sqlStr(r.PlantCode)}, ` +
          `${sqlStr(r.MaterialCode)}, ${sqlStr(r.MaterialDescription)}, ${sqlStr(r.Unit)}, ` +
          `${sqlNum(r.PresentStockDiv)}, ${sqlNum(r.SourceStockAtAllot)}, ${sqlNum(r.ZoneStockAtAllot)}, ` +
          `${sqlNum(r.AllottedQty)}, ${sqlStr(r.Remarks)}, ${sqlStr(r.CreatedBy || 'sheet-migration')}, ` +
          `${sqlTs(r.CreatedAt)}::timestamptz)${comma}`
      );
    });
    lines.push(') AS v(');
    lines.push(
      '  allotment_no, date, movement_type, from_store, from_plant_code, division, plant_code,'
    );
    lines.push(
      '  material_code, material_description, unit, present_stock_div, source_stock_at_allot,'
    );
    lines.push('  zone_stock_at_allot, allotted_qty, remarks, created_by, created_at');
    lines.push(')');
    lines.push('WHERE NOT EXISTS (');
    lines.push('  SELECT 1 FROM mzo_insight.stock_allotments s');
    lines.push('  WHERE s.allotment_no = v.allotment_no');
    lines.push(');');
    lines.push('');
  }

  Object.entries(maxByYear).forEach(([year, maxSeq]) => {
    const next = Number(maxSeq) + 1;
    lines.push(`INSERT INTO mzo_insight.stock_allot_seq (year, next_seq)`);
    lines.push(`VALUES (${year}, ${next})`);
    lines.push(`ON CONFLICT (year) DO UPDATE`);
    lines.push(`SET next_seq = GREATEST(mzo_insight.stock_allot_seq.next_seq, EXCLUDED.next_seq);`);
    lines.push('');
  });

  lines.push('COMMIT;');
  lines.push('');
  lines.push('NOTIFY pgrst, \'reload schema\';');
  lines.push('');
  lines.push('SELECT count(*) AS allotment_lines FROM mzo_insight.stock_allotments;');
  lines.push('SELECT year, next_seq FROM mzo_insight.stock_allot_seq ORDER BY year;');

  const outPath = path.join(__dirname, 'import_stock_allotments.sql');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  console.log('Wrote', outPath);
  console.log('Years/seq', maxByYear);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
